Algorithmic access bake to role
IdentityStream/RoleMining pull request #13
Opened 2024-09-16 12:14 UTC by DanyGoT

2024-09-25 08:33 UTC, ragnarstolsmark requested changes
Da var jeg ferdig med min gjennomgang. Det var mye bra, men litt å ta tak i.

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Library/classes/Jaccard.cs
> +        public double WeightedJaccardIndex { get; set; }
Denne bør tas vekk fra denne klassen siden ikke alle har det. Kan eventuelt lages en subklasse weightedjaccard med denne.

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Library/classes/UserAccess.cs
> +        // TODO, change class to take in only UserID and AccessID. This Access should be extra.
Er dette gjort? Eller skal klassen ha et annet navn?

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Tests/IAlgorithmTest.cs
> +        void RunCode();
RunCode er ikke en test. Det hører kanskje mer hjemme i konsollprosjektet.

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Tests/IAlgorithmTest.cs
> +        void TestLargeData();
Her burde det kanskje være en definisjon på hva som er large data.

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Tests/IAlgorithmTest.cs
> +        void TestBasicFunctionality();
Her burde det være en definisjon på hva som er basic functionality.

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Tests/IAlgorithmTest.cs
> +    public interface IAlgorithmTest
Kan vurdere om dette interfacet i det hele tatt er nødvendig.

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Tests/JaccardTest.cs
> +    public void RunCode()
Dette hører ikke hjemme i et test prosjekt. Det går eventuelt an å kalle den noe annet og endre asserten til å asserte noe på resultatet.

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Tests/JaccardTest.cs
> +    public void TestLargeData()
Hva er large data?

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Tests/JaccardTest.cs
> +    public void TestBasicFunctionality()
Denne metoden kan godt få et spesifikt navn knyttet til akkurat hva den tester.

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Tests/RoleSummarizerTest.cs
> +    public void RunCode()
Dette hører ikke hjemme i et test prosjekt. Det går eventuelt an å kalle den noe annet og endre asserten til å asserte noe på resultatet.

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Tests/RoleSummarizerTest.cs
> +        var exception1 = Assert.Throws<ArgumentException>(() => RoleMining.SummarizeRoles(userAccesses, userInRoles));
Kan bytte disse til fluent assertions også.

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Tests/RoleSummarizerTest.cs
> +    public void TestBasicFunctionality()
Denne metoden kan godt få et spesifikt navn knyttet til akkurat hva den tester.

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Tests/RoleSummarizerTest.cs
> +        Assert.NotNull(result);
Disse også kan byttes ut til fluent assertions.

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Tests/RoleSummarizerTest.cs
> +    public void TestLargeData()
Hva er large data?

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Tests/RoleSummarizerTest.cs
> +        Assert.Equal(2, result.Count);
Dette bør byttes ut med fluent assertions.

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Tests/RoleSummarizerTest.cs
> +        Assert.Equal(4, result.Count);
Dette bør byttes ut med fluent assertions.

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Tests/WeightedJaccardTest.cs
> +    public void RunCode()
Dette hører ikke hjemme i et test prosjekt. Det går eventuelt an å kalle den noe annet og endre asserten til å asserte noe på resultatet.

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Tests/WeightedJaccardTest.cs
> +        Assert.NotNull(user1Role1Access1);
Dette bør byttes ut med fluent assertions.

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Tests/WeightedJaccardTest.cs
> +    public void TestJaccardIndices()
Hva tester denne egentlig? Jeg tenker i forhold til navnet.

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Tests/WeightedJaccardTest.cs
> +        Assert.Equal(expectedWeight, actualWeight, precision: 4); // Precision to 4 decimal places
Denne bør byttes ut med fluent assertions.

2024-09-25 08:33 UTC, ragnarstolsmark commented on RoleMining.Tests/WeightedJaccardTest.cs
> +        Assert.Equal(expectedWeight, actualWeight, precision: 4); // Precision to 4 decimal places
Denne bør byttes ut med fluent assertions.

2024-10-04 13:10 UTC, ragnarstolsmark requested changes
Da er du nesten i mål. Et par småting som gjenstår for å bli kvitt advarslene til github.

2024-10-04 13:10 UTC, ragnarstolsmark commented on RoleMining.Library/classes/Jaccard.cs
> +    /// Return object for the <seealso cref="JaccardIndex.JaccardIndices"/> and <seealso cref="WeightedJaccardIndex.JaccardIndices"/>
Her ser det ut som det er noe feil i cref. Kanskje det er referansen til den slettede filen weighted jaccard den reagerer på.

2024-10-04 13:10 UTC, ragnarstolsmark commented on RoleMining.Tests/JaccardTest.cs
> +    public static IEnumerable<object[]> GetNullOrEmptyValues()
Her klager den på null literal til non-nullable reference type. Du må nok slenge et spørsmålstegn bak object.
I tillegg er det vanlig å referere til Object-klassen i C# med stor O.

2024-10-07 06:07 UTC, DanyGoT commented on RoleMining.Library/classes/Jaccard.cs
> +    /// Return object for the <seealso cref="JaccardIndex.JaccardIndices"/> and <seealso cref="WeightedJaccardIndex.JaccardIndices"/>
Siden weighted jaccard ikke er med i denne versjonen, fjernet jeg denne referansen

2024-10-07 06:07 UTC, DanyGoT commented on RoleMining.Tests/JaccardTest.cs
> +    public static IEnumerable<object[]> GetNullOrEmptyValues()
Endret til Object?[]

2024-10-10 06:50 UTC, ragnarstolsmark reviewed
Snart der igjen :)

2024-10-10 06:50 UTC, ragnarstolsmark commented on RoleMining.Library/Algorithms/JaccardIndex.cs
> +        /// <returns>An ordered list of <see cref="Jaccard"/></returns>
Får advarsel på denne.

2024-10-10 06:50 UTC, ragnarstolsmark commented on RoleMining.Library/ServiceCollectionExtensions.cs
> +    public static class ServiceCollectionExtensions
Her har det komt advarsler som bør fikses.

2024-10-10 06:50 UTC, ragnarstolsmark commented on RoleMining.Library/ServiceCollectionExtensions.cs
> +            RoleBuilderAlgorithm roleBuilderAlgorithm = RoleBuilderAlgorithm.Kcluster)
Bør vente med å legge på disse rolebuilder algoritme tingene til de faktisk eksisterer.

2024-10-10 06:50 UTC, ragnarstolsmark commented on RoleMining.Tests/JaccardTest.cs
> +    public static IEnumerable<Object?[]> GetNullOrEmptyValues()
Beklager denne, men jeg vet jeg sa at Object var med stor O, men etter å ha tenkt litt mer på det og sett litt på koden vi har skrevet har jeg kommet til at det er vanligst å skrive det med liten o. 🤯

2024-10-21 13:34 UTC, ragnarstolsmark approved these changes
LGTM 👏

2024-10-21 13:36 UTC, ragnarstolsmark commented
Det viste seg å være noen konflikter som hindret meg i å få det inn på main-branchen.

2024-10-23 06:13 UTC, merged